name: gtu_question_paper
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^1.5.0
  firebase_auth: ^3.0.2
  cloud_firestore: ^2.5.0
  google_sign_in: ^5.0.7
  flutter_login_facebook: ^1.1.0
  google_fonts: ^2.1.0
  intl: ^0.17.0
  provider: ^6.0.0
  rxdart: ^0.27.1
  collection: ^1.15.0
  equatable: 2.0.3
  flutter_bloc: ^7.2.0
  bloc: ^7.1.0
  flutter_svg: ^0.22.0
  flutter_staggered_animations: ^1.0.0
  auto_size_text: ^3.0.0-nullsafety.0
  flutter_weather_bg_null_safety: ^1.0.0
  flutter_pdfview: ^1.2.1
  path: ^1.8.0
  path_provider: ^2.0.3
  syncfusion_flutter_pdfviewer: ^19.2.60-beta
  flutter_widget_from_html: ^0.7.0
  flutter_gradient_colors: ^2.1.1
  animated_text_kit: ^4.2.0
  flutter_fadein: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  change_app_package_name: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/facebook-logo.png
    - images/google-logo.png
    - images/background.png
    - images/background-2.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
